# Generated by Django 4.0.4 on 2022-08-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cimri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price1', models.CharField(max_length=255)),
                ('price2', models.CharField(max_length=255)),
                ('serial', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='cimritoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('price1', models.CharField(max_length=255, verbose_name='price1')),
                ('price2', models.CharField(max_length=255, verbose_name='price2')),
                ('serial', models.CharField(max_length=255, verbose_name='serial')),
            ],
        ),
        migrations.CreateModel(
            name='toyfromcimri',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('price1', models.CharField(max_length=255, verbose_name='price1')),
                ('price2', models.CharField(max_length=255, verbose_name='price2')),
                ('serial', models.CharField(max_length=255, verbose_name='serial')),
            ],
        ),
    ]
