# Generated by Django 4.0.4 on 2022-05-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='akakce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('serial_number', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('prices1', models.CharField(max_length=50)),
            ],
        ),
    ]
