# Generated by Django 4.0.4 on 2022-05-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akakce',
            name='prices1',
            field=models.FloatField(),
        ),
    ]
