# Generated by Django 4.0.4 on 2022-08-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cimridata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price1', models.CharField(max_length=255)),
                ('price2', models.CharField(max_length=255)),
                ('serial', models.CharField(max_length=255)),
            ],
        ),
    ]
