# Generated by Django 4.0.4 on 2022-05-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_alter_akakce_prices1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akakce',
            name='prices1',
            field=models.CharField(max_length=50),
        ),
    ]
