# Generated by Django 4.0.4 on 2022-07-20 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the toy's brand", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a toy category', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ToyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, default='imageicon.png', null=True, upload_to='static/images/uploads')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('product_status', models.CharField(blank=True, choices=[('a', 'Available'), ('o', 'On loan'), ('r', 'Reserved')], default='a', help_text='Toy availability', max_length=1)),
                ('age', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ageinterval')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand')),
                ('category', models.ManyToManyField(to='catalog.category')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'age'],
                'permissions': (('can_mark_returned', 'Set product as returned'),),
            },
        ),
        migrations.CreateModel(
            name='ToyRequestList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('toy_from_borrower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toy_from_borrower', to='catalog.toyproduct')),
                ('toy_from_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toy_from_owner', to='catalog.toyproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ToyRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.CharField(help_text='If you have something to add, you can write it here.', max_length=250)),
                ('start_date', models.DateField(help_text='Start date for toy is on ...', null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(help_text='Coming back on ...', null=True, verbose_name='End Date')),
                ('status', models.CharField(default='Pending', max_length=12)),
                ('is_approved', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sender_toy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_toy', to='catalog.toyproduct')),
                ('toy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_toy', to='catalog.toyproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=255, unique=True)),
                ('phone', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(blank=True, default="{% static 'profile.png' %}", null=True, upload_to='')),
                ('user', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter_name', models.TextField(max_length=400)),
                ('comment_body', models.TextField(max_length=400)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter_user', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='catalog.toyproduct')),
            ],
        ),
    ]
