# Generated by Django 4.0.4 on 2022-08-03 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_alter_person_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.CharField(help_text='If you have something to add, you can write it here.', max_length=250)),
                ('start_date', models.DateField(help_text='Start date for toy is on ...', null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(help_text='Coming back on ...', null=True, verbose_name='End Date')),
                ('requested_toy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requestborrow', to='catalog.toyproduct')),
                ('sender', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sender_toy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestsender', to='catalog.toyproduct')),
            ],
            options={
                'ordering': ['sender', 'sender_toy', 'requested_toy'],
            },
        ),
    ]
