# Generated by Django 4.0.4 on 2022-05-15 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_toyprices_akakce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toyprices_akakce',
            name='prices2',
        ),
    ]
