# Generated by Django 4.0.4 on 2022-05-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_toyprices_akakce_prices2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToyPrices_Akakce',
        ),
    ]
