# Generated by Django 4.0.4 on 2022-05-15 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_akakce'),
    ]

    operations = [
        migrations.DeleteModel(
            name='akakce',
        ),
    ]
