# Generated by Django 4.0.4 on 2022-08-04 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_request_productrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toyrequestlist',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='toyrequestlist',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='toyrequestlist',
            name='toy_from_borrower',
        ),
        migrations.RemoveField(
            model_name='toyrequestlist',
            name='toy_from_owner',
        ),
        migrations.DeleteModel(
            name='ToyRequest',
        ),
        migrations.DeleteModel(
            name='ToyRequestList',
        ),
    ]
