# Generated by Django 4.0.4 on 2022-05-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_pic',
            field=models.ImageField(blank=True, default="{% static 'profile.png' %}", null=True, upload_to=''),
        ),
    ]
