# Generated by Django 4.0.4 on 2022-08-05 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_toyrequestlist_borrower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequest',
            name='requested_toy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestborrow', to='catalog.toyproduct'),
        ),
    ]
