# Generated by Django 4.0.4 on 2022-08-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_requestfortoy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductRequest',
        ),
    ]
