# Generated by Django 4.0.4 on 2022-08-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_delete_productrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='toyproduct',
            name='image',
            field=models.ImageField(blank=True, default='imageicon.png', null=True, upload_to='uploads'),
        ),
    ]
