# Generated by Django 4.0.4 on 2022-08-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_person_profile_pic_alter_toyproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfortoy',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
