# Generated by Django 4.0.4 on 2022-08-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_requestfortoy_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfortoy',
            name='is_ignored',
            field=models.BooleanField(default=False),
        ),
    ]
