# Generated by Django 4.0.4 on 2022-08-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_datafromcimri_price1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafromcimri',
            name='price1',
            field=models.FloatField(),
        ),
    ]
