# Generated by Django 4.0.4 on 2022-08-13 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_datafromcimri_price1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafromcimri',
            name='price1',
        ),
    ]
